// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_HaVk-0R-2iFcc5O9wFSJvlwXajESIMk',
    appId: '1:7031551502:web:e7d1b7330c564fd83c6e5f',
    messagingSenderId: '7031551502',
    projectId: 'falguni-admin',
    authDomain: 'falguni-admin.firebaseapp.com',
    storageBucket: 'falguni-admin.appspot.com',
    measurementId: 'G-DDSSY84LHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIG4hrwrTleFvlUvNuf9fD3PEqUH3Q2dI',
    appId: '1:7031551502:android:9a9ac6901f35a9f23c6e5f',
    messagingSenderId: '7031551502',
    projectId: 'falguni-admin',
    storageBucket: 'falguni-admin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Ardwk1FaJtHaNSDuk5i30xzJbObNb4c',
    appId: '1:7031551502:ios:a4c3b1dd8cf2e9e93c6e5f',
    messagingSenderId: '7031551502',
    projectId: 'falguni-admin',
    storageBucket: 'falguni-admin.appspot.com',
    androidClientId: '7031551502-3nppq56df8jiiuqr469lpgbn94klv53j.apps.googleusercontent.com',
    iosClientId: '7031551502-8m6p4qv7d6svsri6nvavgi7a2643665a.apps.googleusercontent.com',
    iosBundleId: 'com.falgunigruhudhyog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Ardwk1FaJtHaNSDuk5i30xzJbObNb4c',
    appId: '1:7031551502:ios:a538cf726ee8caf13c6e5f',
    messagingSenderId: '7031551502',
    projectId: 'falguni-admin',
    storageBucket: 'falguni-admin.appspot.com',
    androidClientId: '7031551502-3nppq56df8jiiuqr469lpgbn94klv53j.apps.googleusercontent.com',
    iosClientId: '7031551502-u0a2ok2nn9rqogksfvlal19eftt3ddch.apps.googleusercontent.com',
    iosBundleId: 'com.example.falguniLatestLatestUserApp.RunnerTests',
  );
}